repos:
  - repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
      - id: black
        language_version: python3.10
        exclude: processor/database/alembic/versions/

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.11.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]